// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: auth.sql

package database

import (
	"context"
)

const getPasswordHash = `-- name: GetPasswordHash :one
SELECT password
FROM mailbox
WHERE username = ?
  AND active > 0
`

func (q *Queries) GetPasswordHash(ctx context.Context, username string) (string, error) {
	row := q.db.QueryRowContext(ctx, getPasswordHash, username)
	var password string
	err := row.Scan(&password)
	return password, err
}
