// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import ()

type Mailbox struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Active   int32  `json:"active"`
}
